// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ATooltip: typeof import('ant-design-vue/es')['Tooltip']
    Component: typeof import('./src/components/PageDesign/SiderLeft/Component.vue')['default']
    DomTree: typeof import('./src/components/PageDesign/SiderLeft/DomTree.vue')['default']
    'DomTree copy': typeof import('./src/components/PageDesign/SiderLeft/DomTree copy.vue')['default']
    DrawContent: typeof import('./src/components/PageDesign/SiderLeft/DrawContent.vue')['default']
    Drawer: typeof import('./src/components/PageDesign/SiderLeft/Drawer.vue')['default']
    DrawerContent: typeof import('./src/components/PageDesign/SiderLeft/DrawerContent.vue')['default']
    Header: typeof import('./src/components/PageDesign/Header/index.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    PageDesign: typeof import('./src/components/PageDesign/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SiderLeft: typeof import('./src/components/PageDesign/SiderLeft/index.vue')['default']
  }
}

export {}
